import streamlit as st
import pandas as pd
import plotly.express as px
import tiktoken
import html
import os

# Set page configuration
st.set_page_config(
    page_title="LLM Comparison & Tokenization Benchmarking",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Styling (Grounded & Professional Styling)
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Inter', sans-serif;
    }
    
    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        color: #1E293B;
        margin-bottom: 0.2rem;
    }
    
    .subtitle {
        font-size: 1.1rem;
        color: #64748B;
        margin-bottom: 2rem;
    }
    
    .section-header {
        font-size: 1.5rem;
        font-weight: 600;
        color: #0F172A;
        margin-top: 1.5rem;
        margin-bottom: 1rem;
    }

    .card {
        background-color: #F8FAFC;
        border: 1px solid #E2E8F0;
        border-radius: 12px;
        padding: 20px;
        margin-bottom: 20px;
    }
    
    .token-container {
        font-family: monospace;
        line-height: 2.0;
        padding: 15px;
        border-radius: 8px;
        background-color: #0F172A;
        color: #F8FAFC;
        border: 1px solid #1E293B;
    }
</style>
""", unsafe_allow_html=True)

# Helper function to load text data
def load_text(file_path):
    if not os.path.exists(file_path):
        return f"Error: `{file_path}` not found."
    with open(file_path, "r", encoding="utf-8") as f:
        return f.read()

# Load source files
source_document = load_text("data/source_document_rag_vs_long_context.txt")
evaluation_prompt = load_text("data/evaluation_prompt_template.txt")

# Load model summaries (updated models)
summaries = {
    "Claude 4.7 Sonnet": load_text("data/summaries/summary_claude_4_7_sonnet.txt"),
    "GPT 5.5 Instant": load_text("data/summaries/summary_gpt_5_5_instant.txt"),
    "Gemini 3.1 Pro": load_text("data/summaries/summary_gemini_3_1_pro.txt"),
    "DeepSeek-R1": load_text("data/summaries/summary_deepseek_r1.txt"),
    "Llama 3.3 (70B)": load_text("data/summaries/summary_llama_3_3_70b.txt")
}

# Sidebar Info
st.sidebar.markdown("## 📋 Task Details")
st.sidebar.markdown(
    "**Objective:** Evaluate and compare the performance of different Large Language Models (LLMs) "
    "on a document summarization task."
)
st.sidebar.markdown("---")
st.sidebar.markdown("### 🛠️ Evaluation Criteria")
st.sidebar.markdown(
    "1. **Summary Quality:** Well-structured and easy to understand.\n"
    "2. **Accuracy:** Correctly represents source information.\n"
    "3. **Conciseness:** Avoids unnecessary details.\n"
    "4. **Hallucinations:** No information outside the source text."
)

st.markdown("<div class='main-title'>LLM Comparison Dashboard</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Document Summarization & Tokenization Analysis</div>", unsafe_allow_html=True)

# Tab setup
tab_summary, tab_tokenizer, tab_economics = st.tabs([
    "📊 Summary Evaluation", 
    "🔠 Tokenizer Visualizer", 
    "💰 Cost & Caching Simulator"
])

# -------------------------------------------------------------
# TAB 1: SUMMARY COMPARISON
# -------------------------------------------------------------
with tab_summary:
    st.markdown("<div class='section-header'>Document Summarization Benchmarking</div>", unsafe_allow_html=True)
    st.markdown(
        "Compare the summarization outputs generated by five leading LLMs. "
        "Each model processed the same source document using an identical prompt to ensure a fair comparison."
    )
    
    with st.expander("📝 View Source Document (data/source_document_rag_vs_long_context.txt)"):
        st.text_area("Source Text", source_document, height=250, disabled=True)
        
    with st.expander("📋 View Evaluation Prompt (data/evaluation_prompt_template.txt)"):
        st.code(evaluation_prompt, language="text")

    st.markdown("---")
    
    # Model Selection dropdowns
    col_left, col_right = st.columns(2)
    with col_left:
        model_a = st.selectbox("Select Model A", list(summaries.keys()), index=0)
    with col_right:
        model_b = st.selectbox("Select Model B", list(summaries.keys()), index=1)
        
    col_sum_a, col_sum_b = st.columns(2)
    with col_sum_a:
        st.markdown(f"### {model_a} Summary")
        st.markdown(f"<div class='card'>{summaries[model_a]}</div>", unsafe_allow_html=True)
        
    with col_sum_b:
        st.markdown(f"### {model_b} Summary")
        st.markdown(f"<div class='card'>{summaries[model_b]}</div>", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("<div class='section-header'>Performance Evaluation Matrix</div>", unsafe_allow_html=True)
    st.markdown(
        "Evaluate the models below based on their outputs. "
        "The default scores are calibrated based on manual assessments of the generated summaries."
    )

    # Dictionary containing default score matrix for the models
    default_scores = {
        "Claude 4.7 Sonnet": {"Quality": 9.6, "Accuracy": 9.5, "Conciseness": 9.4, "Hallucinations": 10.0},
        "GPT 5.5 Instant": {"Quality": 9.4, "Accuracy": 9.7, "Conciseness": 9.0, "Hallucinations": 10.0},
        "Gemini 3.1 Pro": {"Quality": 9.2, "Accuracy": 9.5, "Conciseness": 8.7, "Hallucinations": 9.8},
        "DeepSeek-R1": {"Quality": 9.5, "Accuracy": 9.7, "Conciseness": 9.1, "Hallucinations": 10.0},
        "Llama 3.3 (70B)": {"Quality": 8.9, "Accuracy": 9.1, "Conciseness": 8.6, "Hallucinations": 9.7}
    }

    # Custom sliders to tune evaluation scores
    st.markdown("#### Fine-Tune Model Scores")
    tuned_scores = {}
    cols_sliders = st.columns(len(default_scores))
    for idx, (model_name, scores) in enumerate(default_scores.items()):
        with cols_sliders[idx]:
            st.markdown(f"**{model_name}**")
            q = st.slider(f"Quality", 0.0, 10.0, float(scores["Quality"]), 0.1, key=f"q_{model_name}")
            a = st.slider(f"Accuracy", 0.0, 10.0, float(scores["Accuracy"]), 0.1, key=f"a_{model_name}")
            c = st.slider(f"Conciseness", 0.0, 10.0, float(scores["Conciseness"]), 0.1, key=f"c_{model_name}")
            h = st.slider(f"No Hallucinations", 0.0, 10.0, float(scores["Hallucinations"]), 0.1, key=f"h_{model_name}")
            
            # Weighted average: 30% Quality, 35% Accuracy, 20% Conciseness, 15% No Hallucinations
            overall = q * 0.3 + a * 0.35 + c * 0.2 + h * 0.15
            tuned_scores[model_name] = {
                "Summary Quality": q,
                "Accuracy": a,
                "Conciseness": c,
                "No Hallucinations": h,
                "Overall Score": round(overall, 2)
            }

    # Render Plotly comparison chart
    chart_data = []
    for model_name, metrics in tuned_scores.items():
        for metric, score in metrics.items():
            if metric != "Overall Score":
                chart_data.append({
                    "Model": model_name,
                    "Metric": metric,
                    "Score": score
                })
    chart_df = pd.DataFrame(chart_data)

    fig = px.bar(
        chart_df, 
        x="Metric", 
        y="Score", 
        color="Model", 
        barmode="group",
        title="Comparative Scores by Evaluation Metric",
        color_discrete_sequence=["#2563EB", "#10B981", "#F59E0B", "#EF4444", "#8B5CF6"],
    )
    fig.update_layout(yaxis_range=[0, 10], plot_bgcolor="rgba(0,0,0,0)")
    st.plotly_chart(fig, use_container_width=True)

    # Render comparison table
    st.markdown("#### Performance Results Table")
    table_rows = []
    for model_name, metrics in tuned_scores.items():
        row = {"Model": model_name}
        row.update(metrics)
        table_rows.append(row)
    
    st.table(pd.DataFrame(table_rows))

    # Researcher Conclusion
    st.markdown("""
    <div class='card'>
        <h3>🔬 Summary of Model Observations</h3>
        <ul>
            <li><strong>Claude 4.7 Sonnet:</strong> Achieved outstanding conciseness and structural alignment. Synthesized key architectural tradeoffs (such as $O(N^2)$ attention limits and DB management costs) while avoiding conversational filler.</li>
            <li><strong>GPT 5.5 Instant & DeepSeek-R1:</strong> Leveraged internal reasoning/chains-of-thought to ensure strict compliance with length and format constraints. Captured specific technical details (citing exact authors and recall curves) with near-zero hallucinations.</li>
            <li><strong>Gemini 3.1 Pro:</strong> Showed highly structured outputs specifying detailed context-window capabilities, though it was slightly more verbose in its formatting.</li>
            <li><strong>Llama 3.3 (70B):</strong> Delivered clean, easy-to-read takeaways with very low latency, though it omitted a few minor technical points (like specific citations).</li>
        </ul>
    </div>
    """, unsafe_allow_html=True)

# -------------------------------------------------------------
# TAB 2: INTERACTIVE TOKENIZER VISUALIZER
# -------------------------------------------------------------
with tab_tokenizer:
    st.markdown("<div class='section-header'>Tokenizer Visualizer</div>", unsafe_allow_html=True)
    st.markdown(
        "Tokenization maps characters into numerical indices that LLMs read. "
        "Compare how text splits differ between the older `cl100k_base` tokenizer (GPT-4) "
        "and the newer `o200k_base` tokenizer (GPT-4o/o1/GPT 5.5)."
    )

    default_token_text = (
        "Retrieval-Augmented Generation (RAG) is a modular, multi-turn system. "
        "It splits text into chunks, indexes them in vector databases, and performs k-NN lookup."
    )
    
    user_text = st.text_area(
        "Input text for tokenization:", 
        value=default_token_text,
        height=100
    )

    if user_text:
        # Load tokenizers
        cl100_enc = tiktoken.get_encoding("cl100k_base")
        o200_enc = tiktoken.get_encoding("o200k_base")

        tokens_cl100 = cl100_enc.encode(user_text)
        tokens_o200 = o200_enc.encode(user_text)

        col_left_tok, col_right_tok = st.columns(2)

        # Highlight color palette for token visualizer
        colors = ["#2563EB", "#D97706", "#059669", "#DC2626", "#7C3AED", "#0891B2"]
        # Light colors for spans to keep text legible inside dark container
        span_bg_colors = ["rgba(37, 99, 235, 0.2)", "rgba(217, 119, 6, 0.2)", "rgba(5, 150, 105, 0.2)", "rgba(220, 38, 38, 0.2)", "rgba(124, 58, 237, 0.2)", "rgba(8, 145, 178, 0.2)"]

        # Tokenizer CL100K Base
        with col_left_tok:
            st.markdown("### `cl100k_base` Tokenizer (GPT-4)")
            st.metric("Total Tokens", len(tokens_cl100), delta=f"{(len(user_text)/len(tokens_cl100)):.2f} chars/token", delta_color="off")
            
            html_cl100 = []
            for idx, token in enumerate(tokens_cl100):
                token_bytes = cl100_enc.decode_single_token_bytes(token)
                token_str = token_bytes.decode('utf-8', errors='replace')
                token_str_esc = html.escape(token_str)
                color = colors[idx % len(colors)]
                bg = span_bg_colors[idx % len(span_bg_colors)]
                html_cl100.append(f'<span style="background-color: {bg}; border: 1px solid {color}; color: #F1F5F9; padding: 2px 4px; border-radius: 4px; margin: 2px; display: inline-block; font-size: 14px;">{token_str_esc}</span>')
            
            st.markdown(f"<div class='token-container'>{''.join(html_cl100)}</div>", unsafe_allow_html=True)

        # Tokenizer o200k Base
        with col_right_tok:
            st.markdown("### `o200k_base` Tokenizer (GPT-4o/o1/GPT 5.5)")
            st.metric("Total Tokens", len(tokens_o200), delta=f"{(len(user_text)/len(tokens_o200)):.2f} chars/token", delta_color="inverse")
            
            html_o200 = []
            for idx, token in enumerate(tokens_o200):
                token_bytes = o200_enc.decode_single_token_bytes(token)
                token_str = token_bytes.decode('utf-8', errors='replace')
                token_str_esc = html.escape(token_str)
                color = colors[idx % len(colors)]
                bg = span_bg_colors[idx % len(span_bg_colors)]
                html_o200.append(f'<span style="background-color: {bg}; border: 1px solid {color}; color: #F1F5F9; padding: 2px 4px; border-radius: 4px; margin: 2px; display: inline-block; font-size: 14px;">{token_str_esc}</span>')
            
            st.markdown(f"<div class='token-container'>{''.join(html_o200)}</div>", unsafe_allow_html=True)

        st.markdown("---")
        st.markdown("#### 💡 How Vocabularies Influence Processing Efficiency")
        st.markdown(
            """
            * **Vocabulary Sizes:** 
              - Older tokenizers like `cl100k_base` use a vocabulary size of $\\approx 100,000$ unique tokens.
              - The newer `o200k_base` tokenizer models expand this vocabulary to $\\approx 200,000$ tokens. Similarly, Llama 3/3.3 uses a $128,256$ vocabulary, and Gemini uses a $256,000$ SentencePiece vocabulary.
            * **Efficiency Gains:** 
              - Larger vocabularies compress text more efficiently (fewer tokens per document). 
              - This reduces both inference times and API costs because providers charge on a per-token basis.
            """
        )

# -------------------------------------------------------------
# Tab 3 stub will be added next
